###AJOUTER MEMBRE
POST http://localhost:8080/salon/utilisateur/SidBaptie?email=1234657@gmail.com

###RECUPER UTILISATEUR PAR EMAIL
GET http://localhost:8080/salon/utilisateurs/mail/1234657@gmail.com


###CREATION SALON : 201
POST http://localhost:8080/salon?nomCreateur=pseudo&nomSalon=Salon3
Content-Type: application/x-www-form-urlencoded
Accept: */*
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNjgzMDAxLCJpYXQiOjE3MTM2NDcwMDEsInNjb3BlIjoiIn0.T9pKO78U1wYj8kyl2gr7Ks7HrWuz7OQTc7Uq1I5fsxc9exINwYMtbCq4bqZCFEin0JT7_igc2FRwuz8rrJKGuOr6f_rqJkML4jMA4MNyhnIs_ZAB1XpaUpk83QM7I9zqXiMHQZ6y0iVzvqKvEGGHEovgR4JWYObyrULKhDARQh824ZiUXUGqAuN6PutpkrvdYDkyrFRh5rbEMAzDi6XGWlv0JEs0q7gb42VURrx5gDE-c_6SpQPb-_ikZt0gvsYCFxvcnj1AvS93xEOxrMAnhuey3ANdIqgScyOSOV6Sbv_0KDnRabAC7cka8PujCudyTCHPiIhjJ_6aK3PTFn9Ccg

###GET SALON BY NAME : 200
GET http://localhost:8080/salon/byname/Salon3
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNjgzMDAxLCJpYXQiOjE3MTM2NDcwMDEsInNjb3BlIjoiIn0.T9pKO78U1wYj8kyl2gr7Ks7HrWuz7OQTc7Uq1I5fsxc9exINwYMtbCq4bqZCFEin0JT7_igc2FRwuz8rrJKGuOr6f_rqJkML4jMA4MNyhnIs_ZAB1XpaUpk83QM7I9zqXiMHQZ6y0iVzvqKvEGGHEovgR4JWYObyrULKhDARQh824ZiUXUGqAuN6PutpkrvdYDkyrFRh5rbEMAzDi6XGWlv0JEs0q7gb42VURrx5gDE-c_6SpQPb-_ikZt0gvsYCFxvcnj1AvS93xEOxrMAnhuey3ANdIqgScyOSOV6Sbv_0KDnRabAC7cka8PujCudyTCHPiIhjJ_6aK3PTFn9Ccg


###MODIFIER SALON : 200
PATCH http://localhost:8080/salon/1
Content-Type: application/json

{
  "choix": "nom",
  "valeur": "nouveauNom"
}

###GET SALON BY NUM : 200
GET http://localhost:8080/salon/1



###GET UTILISATEUR PAR PSEUDO : 200
GET http://localhost:8080/salon/getUtilisateur/Vince


### CREER EVENEMENT
POST http://localhost:8080/salon/1/evenement
Content-Type: application/json
Accept: application/json

{
  "nomCreateur": "NomUtilisateur",
  "nomEvenement": "NomEvenement",
  "nombrePersonneMax": 1,
  "detailsEvenement": "Détails de l'événement",
  "lieu": "Lieu de l'événement",
  "date": "2024-04-20T12:00:00"
}

###MODIFIER EVENEMENT : 200
PATCH http://localhost:8080/salon/1/evenement/1
Content-Type: application/json
Accept: application/json

{
  "choix": "nom",
  "valeur": "nouvelleValeur"
}

###SE METTRE PRESENT A UN EVENEMENT
POST http://localhost:8080/salon/1/evenement/1/presence?nomUtilisateur=Vince

###SE RETIRER D'UN EVENEMENT
DELETE http://localhost:8080/salon/1/evenement/1/presence?nomUtilisateur=Vince
Content-Type: application/json





### RECUPERER L'EVENEMENT : 200
GET http://localhost:8080/salon/1/evenement/1

### VALIDER EVENEMENT
PATCH http://localhost:8080/salon/1/evenement/1/validation

###ENVOYER UN MESSAGE SUR LE SALON
POST http://localhost:8080/salon/1/messages
Content-Type: application/json
Accept: application/json

{
  "auteur": "Vince",
  "contenu": "Coucou moi",
  "date": "14/01/1998"
}

###ENVOYER UN MSG DANS L'EVENEMENT
POST http://localhost:8080/salon/1/evenement/1/messages
Content-Type: application/json
Accept: application/json

{
  "auteur": "Vince",
  "contenu": "Bonjour à tous !",
  "date": "15/01/1998"
}

###RECUPERER MESSAGES DU SALON
GET http://localhost:8080/salon/1/messages

###RECUPER MESSAGES DE l'EVENEMENT
GET http://localhost:8080/salon/1/evenement/1/messages

###REJOINDRE SALON
POST http://localhost:8080/salon/1/adhesion?pseudoUtilisateur=Vince
Content-Type: application/json

###SUPPRIMER UTILISATEUR : 204
DELETE http://localhost:8080/salon/utilisateur/Camacho

###RECUP DONNEES UTILISATEUR
GET http://localhost:8080/salon/utilisateur/Vince

###AJOUTER MODERATEUR
POST http://localhost:8080/salon/1/moderation?nomModerateur=Vince

###SUPPRIMER MODERATEUR
DELETE http://localhost:8080/salon/1/moderation?nomModerateur=Vince

### RECUPERER LES SALONS DE l'UTILISATEUR
GET http://localhost:8080/salon/utilisateur/tomas/salons
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidG9tYXMiLCJleHAiOjE3MTM3NDc5ODMsImlhdCI6MTcxMzcxMTk4Mywic2NvcGUiOiIifQ.AlEr7O25weBQsxHveHWbdOwUgYMqUyC_0dHjVLLZvAwSHEWL6Xn5RT10PfHOxYO_7FLEpubVPm-2l92LxKdDQURHoQLV1BCI6rKEkO1QaSP60AiiRtBw5-7LUCVJQcWq0jxLPXYnToByYE1domqBth2l_VZYRSdYMC--FNg2o24FTY6pA30WtwR7wtwTq4jJNyc0SvBAnj3EttVfIhqRZz1tft5HgEp_5stUTMHO_ZijXsueil-Q5rbh_WvvyIgl52fuZLZVO374ps0XBBFZ_KW1G4fZg3NTJFHjTsXvqO3I57jGfxsWidXitmO9hwZzOIVlp3IoRPb_I2mYyODNjw

### RECUPERER LES EVENEMENTS DE L'UTILISATEUR
GET http://localhost:8080/salon/utilisateur/Vince/evenements



