
###Inscription Personne expected = 201
POST http://localhost:8080/auth/inscription?pseudo=test222&mdp=test222&eMail=test222
Content-Type: application/x-www-form-urlencoded
Accept: */*

###Test
PATCH http://localhost:8080/auth/modification-pseudo?pseudo=test2224&nouveauPseudo=test22245
Content-Type: application/json

###Test
DELETE http://localhost:8080/auth/suppression?pseudo=vincent3&mdp=mdpfdp
Content-Type: application/json


###connexion Personne expected = 201
POST http://localhost:8080/auth/connexion
Content-Type: application/x-www-form-urlencoded
Accept: */*

pseudo=bibi&mdp=lustucru

###Token Personne expected = 201
GET http://localhost:8080/auth/token?token=4e141818-7734-4efe-8d85-ed6b776f23fe

###TestInscriptionFull
POST http://localhost:8080/utilisateurs/inscription
Content-Type: application/x-www-form-urlencoded
Accept: */*

pseudo=sid&mdp=baptielpb&email=vincentlpb@camacho.fr&bio=salutcmoi&photoDeProfil=www.googleimage.fr/sidlpb

### recuperer infos publiques
GET http://localhost:8080/utilisateurs/sid

###
POST http://localhost:8080/utilisateurs/suppressionCompte
Content-Type: application/x-www-form-urlencoded
Accept: */*

email=vincentlpb@camacho.fr

### TEST CREATION SALON
POST http://localhost:8080/salon?nomCreateur=vincent52&nomSalon=SuperSalon
Authorization: Bearer f277fb35-f726-4525-b0d1-4ad611413b1b
Content-Type: application/json


###TEST UTILISATEUR INSCRIPTION
POST http://localhost:8080/utilisateurs/inscription?pseudo=John2&email=john@example2.com&bio=Hello%20World&photoDeProfil=profile.jpg


###Inscription Personne expected = 201
POST http://localhost:8080/auth/inscription?pseudo=vincent52&mdp=vincent52&eMail=vincent.aubert5@evnt2.com
Content-Type: application/x-www-form-urlencoded
Accept: */*

###TEST CONNEXION
POST http://localhost:8080/auth/connexion?pseudo=vincent52&mdp=vincent52

