###TestInscriptionFull
POST http://localhost:8080/utilisateurs/inscription
Content-Type: application/x-www-form-urlencoded
Accept: */*

pseudo=sid&mdp=baptielpb&email=vincentlpb@camacho.fr&bio=salutcmoi&photoDeProfil=www.googleimage.fr/sidlpb


###ChangerPseudo expected=200
PATCH http://localhost:8080/utilisateurs/changementPseudo?email=vincentlpb@camacho.fr&nouveauPseudo=new_pseudo



###changementBio expected=200
PATCH http://localhost:8080/utilisateurs/changementBio?email=vincentlpb@camacho.fr&nouvelleBio=new_bio


###changementPhotoDeProfil expected=200
PATCH http://localhost:8080/utilisateurs/changementPhotoDeProfil?email=vincentlpb@camacho.fr&nouvellePhotoDeProfil=new_photo

###GET INFO COMPTE Expecte =200
GET http://localhost:8080/utilisateurs/new_pseudo


###AJOUT CONTACT expected = 200
POST http://localhost:8080/utilisateurs/ajoutContact?pseudo1=new_pseudo&pseudo2=vince


###DELETE COMPTE Expected = 200
DELETE http://localhost:8080/utilisateurs/suppressionCompte?email=vincentlpb@camacho.fr




###Modification mdp expected = 200
PATCH http://localhost:8080/auth/modification-mdp?pseudo=pseudo_new&mdp=mdp&nouveauMDP=mdp2
Content-Type: application/x-www-form-urlencoded
Accept: */*

###Modification pseudo expected = 200
PATCH http://localhost:8080/auth/modification-pseudo?pseudo=pseudo&nouveauPseudo=pseudo_new
Content-Type: application/x-www-form-urlencoded
Accept: */*

###Suppression expected = 200
DELETE http://localhost:8080/auth/suppression?pseudo=pseudo_new&mdp=mdp2
Content-Type: application/json

###Déconnexion expected=200
POST http://localhost:8080/auth/deconnexion?pseudo=vincent52&mdp=vincent52

