### AJOUTER UN UTILISATEUR
POST http://localhost:8080/google/utilisateur/email=test@evnt.com
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzM1NzcxLCJpYXQiOjE3MTM2OTk3NzEsInNjb3BlIjoiIn0.hLmWOrkGKmuh1VFaVAC48uWjSMy-apFTBsOSlmnOK258n00SzvQ3EjXLPniSwwV-y7W-ZHqvkGuuaxyCVtRV3-OcjEkGCB2v5GFKCPPdgVZ-u7qcYMSB0QLCcU5sq76VjrkpXawwv2WKy62McbC2KAOLRWhMtu5nWo9gBAaFMuuJTnyf8xzk5mt_nCVNCPZw0gw8mY1hZAKHnVxEWCixdqFkImWyQn9WfrXlPu6WwoTcudd0scKngBa1FPTHfi2QOhmC80-qIwohbgUYQpbpY4Fk4BfA6y-5WRJxl1mobwCFx4u2DNEKEdABOmJcT3fMzNcUW5USAK2ef_Hdf_gqFg

### TEST
POST http://localhost:8080/google/utilisateur/example@example.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzM1NzcxLCJpYXQiOjE3MTM2OTk3NzEsInNjb3BlIjoiIn0.hLmWOrkGKmuh1VFaVAC48uWjSMy-apFTBsOSlmnOK258n00SzvQ3EjXLPniSwwV-y7W-ZHqvkGuuaxyCVtRV3-OcjEkGCB2v5GFKCPPdgVZ-u7qcYMSB0QLCcU5sq76VjrkpXawwv2WKy62McbC2KAOLRWhMtu5nWo9gBAaFMuuJTnyf8xzk5mt_nCVNCPZw0gw8mY1hZAKHnVxEWCixdqFkImWyQn9WfrXlPu6WwoTcudd0scKngBa1FPTHfi2QOhmC80-qIwohbgUYQpbpY4Fk4BfA6y-5WRJxl1mobwCFx4u2DNEKEdABOmJcT3fMzNcUW5USAK2ef_Hdf_gqFg


### DELETE UN UTILISATEUR
DELETE http://localhost:8080/google/utilisateur?email=test@evnt.com
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNzM1NzcxLCJpYXQiOjE3MTM2OTk3NzEsInNjb3BlIjoiIn0.hLmWOrkGKmuh1VFaVAC48uWjSMy-apFTBsOSlmnOK258n00SzvQ3EjXLPniSwwV-y7W-ZHqvkGuuaxyCVtRV3-OcjEkGCB2v5GFKCPPdgVZ-u7qcYMSB0QLCcU5sq76VjrkpXawwv2WKy62McbC2KAOLRWhMtu5nWo9gBAaFMuuJTnyf8xzk5mt_nCVNCPZw0gw8mY1hZAKHnVxEWCixdqFkImWyQn9WfrXlPu6WwoTcudd0scKngBa1FPTHfi2QOhmC80-qIwohbgUYQpbpY4Fk4BfA6y-5WRJxl1mobwCFx4u2DNEKEdABOmJcT3fMzNcUW5USAK2ef_Hdf_gqFg
