###Inscription Personne expected = 200 OK
POST http://localhost:8080/auth/inscription?pseudo=pseudo&mdp=mdp&eMail=vincent.aubert@evnt2.com
Content-Type: application/x-www-form-urlencoded
Accept: */*

###Connexion expected=200 + token
POST http://localhost:8080/auth/connexion?pseudo=pseudo&mdp=mdp

###Modification mdp expected = 200
PATCH http://localhost:8080/auth/modification-mdp?pseudo=pseudo_new&mdp=mdp2&nouveauMDP=mdp845854
Content-Type: application/x-www-form-urlencoded
Accept: */*
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNjgzMDAxLCJpYXQiOjE3MTM2NDcwMDEsInNjb3BlIjoiIn0.T9pKO78U1wYj8kyl2gr7Ks7HrWuz7OQTc7Uq1I5fsxc9exINwYMtbCq4bqZCFEin0JT7_igc2FRwuz8rrJKGuOr6f_rqJkML4jMA4MNyhnIs_ZAB1XpaUpk83QM7I9zqXiMHQZ6y0iVzvqKvEGGHEovgR4JWYObyrULKhDARQh824ZiUXUGqAuN6PutpkrvdYDkyrFRh5rbEMAzDi6XGWlv0JEs0q7gb42VURrx5gDE-c_6SpQPb-_ikZt0gvsYCFxvcnj1AvS93xEOxrMAnhuey3ANdIqgScyOSOV6Sbv_0KDnRabAC7cka8PujCudyTCHPiIhjJ_6aK3PTFn9Ccg

###Modification pseudo expected = 200
PATCH http://localhost:8080/auth/modification-pseudo?pseudo=pseudo&nouveauPseudo=pseudo_new
Content-Type: application/x-www-form-urlencoded
Accept: */*
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNjgzMDAxLCJpYXQiOjE3MTM2NDcwMDEsInNjb3BlIjoiIn0.T9pKO78U1wYj8kyl2gr7Ks7HrWuz7OQTc7Uq1I5fsxc9exINwYMtbCq4bqZCFEin0JT7_igc2FRwuz8rrJKGuOr6f_rqJkML4jMA4MNyhnIs_ZAB1XpaUpk83QM7I9zqXiMHQZ6y0iVzvqKvEGGHEovgR4JWYObyrULKhDARQh824ZiUXUGqAuN6PutpkrvdYDkyrFRh5rbEMAzDi6XGWlv0JEs0q7gb42VURrx5gDE-c_6SpQPb-_ikZt0gvsYCFxvcnj1AvS93xEOxrMAnhuey3ANdIqgScyOSOV6Sbv_0KDnRabAC7cka8PujCudyTCHPiIhjJ_6aK3PTFn9Ccg

###Déconnexion expected=200
POST http://localhost:8080/auth/deconnexion?pseudo=pseudo_new&mdp=mdp845854
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNjgzMDAxLCJpYXQiOjE3MTM2NDcwMDEsInNjb3BlIjoiIn0.T9pKO78U1wYj8kyl2gr7Ks7HrWuz7OQTc7Uq1I5fsxc9exINwYMtbCq4bqZCFEin0JT7_igc2FRwuz8rrJKGuOr6f_rqJkML4jMA4MNyhnIs_ZAB1XpaUpk83QM7I9zqXiMHQZ6y0iVzvqKvEGGHEovgR4JWYObyrULKhDARQh824ZiUXUGqAuN6PutpkrvdYDkyrFRh5rbEMAzDi6XGWlv0JEs0q7gb42VURrx5gDE-c_6SpQPb-_ikZt0gvsYCFxvcnj1AvS93xEOxrMAnhuey3ANdIqgScyOSOV6Sbv_0KDnRabAC7cka8PujCudyTCHPiIhjJ_6aK3PTFn9Ccg

###Suppression expected = 200
DELETE http://localhost:8080/auth/suppression?pseudo=pseudo_new&mdp=mdp2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidmluY2VudC5hdWJlcnRAZXZudDIuY29tIiwiZXhwIjoxNzEzNjgzMDAxLCJpYXQiOjE3MTM2NDcwMDEsInNjb3BlIjoiIn0.T9pKO78U1wYj8kyl2gr7Ks7HrWuz7OQTc7Uq1I5fsxc9exINwYMtbCq4bqZCFEin0JT7_igc2FRwuz8rrJKGuOr6f_rqJkML4jMA4MNyhnIs_ZAB1XpaUpk83QM7I9zqXiMHQZ6y0iVzvqKvEGGHEovgR4JWYObyrULKhDARQh824ZiUXUGqAuN6PutpkrvdYDkyrFRh5rbEMAzDi6XGWlv0JEs0q7gb42VURrx5gDE-c_6SpQPb-_ikZt0gvsYCFxvcnj1AvS93xEOxrMAnhuey3ANdIqgScyOSOV6Sbv_0KDnRabAC7cka8PujCudyTCHPiIhjJ_6aK3PTFn9Ccg




