###Inscription Personne expected = 200 OK
POST http://localhost:8080/auth/inscription?pseudo=pseudo12&mdp=mdp&eMail=vincent.aubert@evnt12.com
Content-Type: application/x-www-form-urlencoded
Accept: */*

###Inscription Personne expected = 200 OK
POST http://localhost:8080/auth/connexion/pseudo=VinceLeBg&mdp=Ratio


###Connexion expected=200 + token
POST http://localhost:8080/auth/connexion?pseudo=pseudo12&mdp=mdp

###Modification pseudo expected = 200
PATCH http://localhost:8080/auth/modification-pseudo?pseudo=pseudo&nouveauPseudo=pseudo_new
Content-Type: application/x-www-form-urlencoded
Accept: */*

###Modification mdp expected = 200
PATCH http://localhost:8080/auth/modification-mdp?pseudo=pseudo_new&mdp=mdp&nouveauMDP=mdp2
Content-Type: application/x-www-form-urlencoded
Accept: */*

###Suppression expected = 200
DELETE http://localhost:8080/auth/suppression?pseudo=pseudo_new&mdp=mdp2
Content-Type: application/json

###Déconnexion expected=200
POST http://localhost:8080/auth/deconnexion?pseudo=vincent52&mdp=vincent52

